language: haskell
ghc: 7.8
cache:
  directories:
    - $TRAVIS_BUILD_DIR/.cabal-sandbox
    - $TRAVIS_BUILD_DIR/.other_dependancies_sandbox
install:
- cabal sandbox init
- cabal install --only-dependencies --enable-tests
- cd .other_dependancies_sandbox
- cabal install happy-1.19.4
- cabal install hpc-coveralls
- cd ..
- export PATH=$PATH:$TRAVIS_BUILD_DIR/.other_dependancies_sandbox/bin
before_script:
- cabal configure --enable-tests --enable-coverage
- cabal build
script:
- cabal test --show-details=always --test-options="--color"
after_script:
- hpc-coveralls --exclude-dir=tests hunit