language: haskell
ghc: 7.8
cache:
  directories:
    - /home/travis/build/jacekm-git/HsPredictor/.cabal-sandbox
install:
- cabal sandbox init
- cabal install --only-dependencies --enable-tests
before_script:  
- cabal configure --enable-tests
- cabal build
script:  
- cabal test --show-details=always --test-options="--color"