language: haskell
ghc: 7.8
cache:
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/.cabal-sandbox
install:
- apt-get install happy
- cabal sandbox init
- cabal install --only-dependencies --enable-tests
before_script:  
- cabal configure --enable-tests
- cabal build
script:  
- cabal test --show-details=always --test-options="--color"